server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/kotlin_library
    username: postgres
    password: postgrespw
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
  output:
    ansi:
      enabled: ALWAYS

  liquibase:
    enabled: true
    change-log: classpath:db/master/master.xml

